### ISSUE TITLE
Remove JQuery dependency.

### ISSUE THREAD

**Issue by bklik** [humaan/Modaal#29] opened 2016-05-02 13:29 UTC
Looking at your code, I don't really see why you're using JQuery. You could easily remove this dependency by replacing it with native JavaScript calls.

e.g.
var dom = document.body;
var element = document.querySelector('.class-name');
if(element.classList.contains('class-name') {};
element.addEventListener('click|keydown', function);
etc.

**Comment by pzi** [comment] 2016-05-02 13:41
Dupe of #14

**Comment by bklik** [comment] 2016-05-02 13:52
Derp

**Closed** 2016-05-02 13:52 UTC
