### ISSUE TITLE
Angular AJAX call VS. Modaal

### ISSUE THREAD

**Issue by viniciusofp** [humaan/Modaal#89] opened 2017-04-19 03:05 UTC
Hello,

I'm developing a Wordpress theme that uses Angular and the WP REST API. The theme is supposed to load the posts content in a Modaal, via AJAX.

Here's a piece of the HTML code

	
```
<div ng-controller="quemSomos">
         <a href="#inline" class="inline" ng-click="openPost(6)">
		<div class="col-sm-4 col-md-3 col-lg-3 col-md-offset-3 gridpost color">
			<h6>Open Modaal</h6>
		</div>
	</a>
	<div id="inline">
		<div class="container-fluid">
			<div class="row">
			     <div class="col-sm-4">
					<h2>{{ post.title.rendered }}</h2>
			    </div>
			    <div class="col-sm-8" ng-bind-html="post.content.rendered">
			    </div>
		        </div>
		</div>		
	</div>						
</div>
```

And Angular code:

```
angular.module('yodeley', ['ngSanitize', 'ngResource'])
.factory('wp', function ($resource) {

	return $resource("/wp-json/wp/v2/posts/:id?_embed");

})
.controller('quemSomos', ['$scope',  'wp', function($scope,  wp) {


	$scope.posts = wp.query();
	$scope.post = wp.get({id: 361});
	$scope.openPost = function (postId) {
		$scope.post = wp.get({id: postId});
		console.log($scope.post);
	}
}]);
```

The problem is that the view doesn't change when I call the openPost function. I spend hours trying to find the error in Angular, but after a long time I realized it worked perfectly when I render the content outside of the Modaal. Does Modaal have a problem dealing with asynchronous HTTP requests or am I doing it wrong?

**Comment by danhumaan** [comment] 2018-11-06 08:52
Hi, apologies about having completely missed this ticket. I hope this is something you've resolved? We have not used Modaal directly inside Angular ourselves so would need to lean on yourself or others to provide a more detailed reply as to whether your implementation or Modaal is the cause.

For the moment, and due to the age and specificity of the issue raised I'm going to close this unless someone can point to Modaal being the cause of the problem?

**Closed by danhumaan** 2018-11-06 08:52 UTC
